### ISSUE TITLE
Làm thế nào để chạy trình giả lập

### ISSUE THREAD

**Issue by hungpham3112** [makerviet/tfs-auto-algorithms#1]
![image](https://github.com/makerviet/tfs-auto-algorithms/assets/75968004/eaa6ed16-69f7-44fd-9e22-46bc2352ef3c)

Sau khi tải và tiến hành giải nén thì xuất hiện các file trong folder như trên nhưng không có file .exe hay bất kì điều gì liên quan. Xem xét kĩ một lượt README.md thì ko nhận thấy có hướng dẫn nào về điều này.

**Comment by vietanhdev** [comment]
@hungpham3112 Bạn có thể dùng trình giả lập online tại: [https://daisylab.net/via-sim-2023-07-24/](https://daisylab.net/via-sim-2023-07-24/).
